spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.pinapp.customerservice: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:your_development_secret_key}
    expiration: ${SECURITY_JWT_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,beans,conditions
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      group:
        readiness:
          include: db,rabbitmq,diskSpace
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
      slo:
        http.server.requests: 50ms, 100ms, 200ms
  tracing:
    sampling:
      probability: 1.0
  observations:
    key-values:
      application: customer-service