apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/customerdb"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  SPRING_RABBITMQ_USERNAME: "guest"

  # Logging configuration
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_PINAPP_CUSTOMERSERVICE: "INFO"

  # Actuator and metrics
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED: "true"
  MANAGEMENT_OBSERVATIONS_KEY_VALUES_APPLICATION: "customer-service"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"